name: Publish Package to GitHub NPM Registry

on: 
  release:
    types: [published] 
    
jobs:
    npm-package:
      permissions:
         packages: write
      runs-on: ubuntu-latest
      steps:
        - name: Checkout Repository
          uses: actions/checkout@v4
        - name: Setup npm to publish
          uses: actions/setup-node@v4
          with:
             node-version: '20.x'
             registry-url: 'https://registry.npmjs.org'
        - run: npm ci
        - run: npm publish --provenance --access public
          env:
            NODE_AUTH_TOKEN: ${{ secrets.GITHUB_TOKEN }}
        - name: Install dependencies
          run: npm install 
